<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Usman-PC" name="readExcel.DataDrivenDemo" tests="1" failures="0" timestamp="06 Nov 2017 22:41:57 GMT" time="0.000" errors="1">
  <testcase name="testData" time="0.000" classname="readExcel.DataDrivenDemo">
    <error type="org.testng.TestNGException" message="
Some DataProvider public java.lang.Object[][] readExcel.DataDrivenDemo.passData(int,int,int) throws java.lang.Exception parameters unresolved:  at 0 type int
 at 1 type int
 at 2 type int
">
      <![CDATA[org.testng.TestNGException: 
Some DataProvider public java.lang.Object[][] readExcel.DataDrivenDemo.passData(int,int,int) throws java.lang.Exception parameters unresolved:  at 0 type int
 at 1 type int
 at 2 type int

	at org.testng.internal.MethodInvocationHelper.getParameters(MethodInvocationHelper.java:178)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:114)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:612)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1316)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1044)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1134)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testData -->
</testsuite> <!-- readExcel.DataDrivenDemo -->
